import { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast'

import { fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { ThemeProvider } from '@/components/theme-provider'

import '@/styles/globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

type RootLayoutProps = {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<ClerkProvider>
			<html lang='en' className='h-full' suppressHydrationWarning>
				<head />
				<body
					className={cn(
						'h-full bg-background font-sans antialiased',
						fontSans.variable
					)}
				>
					<ThemeProvider attribute='class' defaultTheme='system' enableSystem>
						{children}
						<Toaster />
						<TailwindIndicator />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
