import { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast'

import { fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils/cn'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { TailwindIndicator } from '@/components/tailwind-indicator'

// Uploadthing styles must be imported before global styles
import '@uploadthing/react/styles.css'
import '@/styles/globals.css'

import ReactQueryProvider from '@/components/providers/react-query-provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

type RootLayoutProps = {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<ClerkProvider>
			<ReactQueryProvider>
				<html lang='en' className='h-full' suppressHydrationWarning>
					<body
						className={cn(
							'h-full bg-background font-sans antialiased',
							fontSans.variable
						)}
					>
						<ThemeProvider attribute='class' defaultTheme='system' enableSystem>
							{children}
							<Toaster />
							<TailwindIndicator />
						</ThemeProvider>
					</body>
				</html>
			</ReactQueryProvider>
		</ClerkProvider>
	)
}
